use_frameworks!

platform :ios, '9.0'

target 'SOTools_Example' do
  pod 'SOTools', :path => '../'

  target 'SOTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
